"""initial schema

Revision ID: a80432b5137b
Revises:
Create Date: 2026-10-04 18:40:11.454047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a80432b5137b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "day_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("day_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_day_logs_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_day_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metrics_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_user_id"), ["user_id"], unique=False)

    op.create_table(
        "phase_state",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("week", sa.String(length=8), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("gate_pending", sa.Boolean(), nullable=False),
        sa.Column("bike_stage", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "rides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("miles", sa.Float(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("zone", sa.Integer(), nullable=False),
        sa.Column("commute", sa.String(length=8), nullable=True),
        sa.Column("elevation_ft", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rides", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rides_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_rides_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("week", sa.String(length=8), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("heavy", sa.Boolean(), nullable=False),
        sa.Column("soreness", sa.Integer(), nullable=True),
        sa.Column("sleep", sa.Integer(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "xp_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=60), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("xp_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_xp_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "set_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("exercise", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("prescribed_weight_lb", sa.Float(), nullable=True),
        sa.Column("prescribed_reps", sa.Integer(), nullable=True),
        sa.Column("rpe_cap", sa.Float(), nullable=True),
        sa.Column("rpe_min", sa.Float(), nullable=True),
        sa.Column("rpe_max", sa.Float(), nullable=True),
        sa.Column("weight_lb", sa.Float(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("seconds", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("form_ok", sa.Boolean(), nullable=False),
        sa.Column("pain", sa.String(length=120), nullable=True),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_set_logs_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_set_logs_session_id"))

    op.drop_table("set_logs")
    with op.batch_alter_table("xp_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xp_events_user_id"))

    op.drop_table("xp_events")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_date"))

    op.drop_table("sessions")
    with op.batch_alter_table("rides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rides_user_id"))
        batch_op.drop_index(batch_op.f("ix_rides_date"))

    op.drop_table("rides")
    op.drop_table("phase_state")
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metrics_user_id"))
        batch_op.drop_index(batch_op.f("ix_metrics_date"))

    op.drop_table("metrics")
    with op.batch_alter_table("day_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_day_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_day_logs_date"))

    op.drop_table("day_logs")
    op.drop_table("users")
    # ### end Alembic commands ###
