"""badges table

Revision ID: fc9233cbf784
Revises: a80432b5137b
Create Date: 2026-10-04 19:07:11.281434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc9233cbf784"
down_revision: str | Sequence[str] | None = "a80432b5137b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("earned_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uq_badges_user_key"),
    )
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_badges_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_badges_user_id"))

    op.drop_table("badges")
    # ### end Alembic commands ###
